version: '3.8'
services:
  app:
    build:
      context: . # Use Dockerfile in the current directory
    ports:
      - "8080:8080" # Map host to container ports
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/employee_directory
      SPRING_DATASOURCE_USERNAME: springstudent
      SPRING_DATASOURCE_PASSWORD: springstudent
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - db # Ensure the database starts before the app
  db:
    image: mysql:8.0 # MySQL version 8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: employee_directory
      MYSQL_USER: springstudent
      MYSQL_PASSWORD: springstudent
    ports:
      - "3306:3306" # Map MySQL port
    volumes:
      - db-data:/var/lib/mysql # Persist database data
volumes:
  db-data:
